<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [5]:
def greet(name):
    if name.lower() == "SPIDERMAN":
        return(f'Oh my goddddd you\'re so amazingggg')
    else:
        return(f'Good day, {name}!')

print(greet(input("My name is ")))

My name is potateh
Good day, potateh!


In [6]:
def basic_stats(numbers):
    np_numbers=np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()
basic_stats([1,2,3,4,5,6,7,8,9,10,-55,67,32,4,1])

(-55, 67, 6.933333333333334)

### 1.2 Named functions that don’t return

In [4]:
print("This is a terrible morning")
print(print("The next line is the output of this print function"))

This is a terrible morning
The next line is the output of this print function
None


### 1.3 Anonymous functions

In [10]:
numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]
print(id(numbers))
print(id(sorted(numbers)))
print(sorted(numbers))
# this is different from numbers.sort(), which changes the list in place.
# sorted(numbers) returns a new list
numbers.sort()
print(id(numbers))
print(numbers)

2920361615104
2920383382208
[[0, 9, 19], [1, 8, 18], [2, 7, 17], [3, 6, 16], [4, 5, 15], [5, 4, 14], [6, 3, 13], [7, 2, 12], [8, 1, 11], [9, 0, 10]]
2920361615104
[[0, 9, 19], [1, 8, 18], [2, 7, 17], [3, 6, 16], [4, 5, 15], [5, 4, 14], [6, 3, 13], [7, 2, 12], [8, 1, 11], [9, 0, 10]]


In [16]:
numbers=[[1, 0, 25],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]
print(f'Base list is \n{sorted(numbers)}')
print(f'Sorted by ascending second item: \n{sorted(numbers, key=lambda x: x[1])}')
print(f'Sorted by ascending sum: \n{sorted(numbers, key = lambda x: sum(x))}')
print(f'Sorted by descending sum of squares : \n{sorted(numbers, key = lambda x: x[0]**2 + x[1]**2 + x[2]**2, reverse = True)}')

Base list is 
[[0, 9, 19], [1, 0, 25], [1, 8, 18], [2, 7, 17], [3, 6, 16], [4, 5, 15], [5, 4, 14], [6, 3, 13], [7, 2, 12], [8, 1, 11]]
Sorted by ascending second item: 
[[1, 0, 25], [8, 1, 11], [7, 2, 12], [6, 3, 13], [5, 4, 14], [4, 5, 15], [3, 6, 16], [2, 7, 17], [1, 8, 18], [0, 9, 19]]
Sorted by ascending sum: 
[[8, 1, 11], [7, 2, 12], [6, 3, 13], [5, 4, 14], [4, 5, 15], [3, 6, 16], [1, 0, 25], [2, 7, 17], [1, 8, 18], [0, 9, 19]]
Sorted by descending sum of squares : 
[[1, 0, 25], [0, 9, 19], [1, 8, 18], [2, 7, 17], [3, 6, 16], [4, 5, 15], [5, 4, 14], [6, 3, 13], [7, 2, 12], [8, 1, 11]]


### 1.4 Optional arguments

In [23]:
def sum(a,b,c,square = False):
    if square == True:
        a = a**2
        b = b**2
        c = c**2
    return a + b + c

print(sum(1,2,3, False))
print(sum(1,2,3, True))

6
14


In [26]:
print(1,2,3,4,5)
print(1,2,3,4,5, sep = " and ")

1 2 3 4 5
1 and 2 and 3 and 4 and 5


## 2 The importance of functions?

### 2.1 An argument for functions

A guinea pig engine would be pretty cool tbh they should invent that

### 2.2 A word of caution

With great function power comes great function responsibility

## Exercise 1 :  Do you know why?

In [31]:
def greeting(name):
    if name == "Batman":
        return "Hello Batman! How is the family doing?"
    return f'Hello {name}!'

print(greeting("Batman"))
print(greeting("Frankenstein"))

Hello Batman! How is the family doing?
Hello Frankenstein!


The function above works without an else statement for the if conditional, firstly because the else conditional is optional for if functions. In the case that name == "Batman", the block of code inside the if conditional is executed, followed by moving on to the next line to execute that code. 
However, in this case that doesn't happen. This is because the return inside the if conditional results in the end of the function, since the function already outputs this string and has no need to continue running more lines in the function.
In the alternative case where name != "Batman", the block of code checks name against the conditional, and returns False. As a result, the block of code inside the if conditional is not executed and the function goes on to execute the next line (which is the return function that catches everything that doesn't fulfill the above conditional.

## Exercise 2 :  Calculator functions

In [14]:
import numpy as np

def add(x,y):
    return x+y

def subtract(x,y):
    return x-y

def multiply(x,y):
    return x*y

def divide(x,y):
    if np.any(y == 0): 
        return "Can't be done, will result in division by zero :("
    return x/y
    
x=np.array([36, 34, 44, 76, 27,0,1,2,3,0,1,2,3])
y=np.array([64, 66, 56, 24, 73,3,2,1,0,0,1,2,3])

print(add(x,y))
print(subtract(x,y))
print(multiply(x,y))
print(divide(x,y))

[100 100 100 100 100   3   3   3   3   0   2   4   6]
[-28 -32 -12  52 -46  -3  -1   1   3   0   0   0   0]
[2304 2244 2464 1824 1971    0    2    2    0    0    1    4    9]
Can't be done, will result in division by zero :(


## Exercise 3 :  max_info() with NumPy

In [5]:
import numpy as np
def max_info(numbers):
    np_num = np.array(numbers)
    return f'The maximum number in your list is {np.amax(np_num)} at index {np.argmax(np_num)}, which means that it is item {np.argmax(np_num)+1} for normal human counters.'

numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]
print(max_info(numbers))

The maximum number in your list is 83 at index 2, which means that it is item 3 for normal human counters.
