<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [2]:
import numpy as np

py_characters = ["Forrest Gump", "Wade Wilson", "James Bond"]
py_actors = ["Tom Hanks", "Ryan Reynolds", "Daniel Craig"]

np_characters = np.array(["Forrest Gump", "Wade Wilson", "James Bond"])
np_actors = np.array(["Tom Hanks", "Ryan Reynolds", "Daniel Craig"])

characters_info = {"Forrest Gump":"Tom Hanks","Wade Wilson":"Ryan Reynolds",
                  "James Bond":"Daniel Craig"}

print(py_characters)
print(py_actors)
print(np_characters)
print(np_actors)
print(characters_info)

['Forrest Gump', 'Wade Wilson', 'James Bond']
['Tom Hanks', 'Ryan Reynolds', 'Daniel Craig']
['Forrest Gump' 'Wade Wilson' 'James Bond']
['Tom Hanks' 'Ryan Reynolds' 'Daniel Craig']
{'Forrest Gump': 'Tom Hanks', 'Wade Wilson': 'Ryan Reynolds', 'James Bond': 'Daniel Craig'}


### 1.2 Accessing data from a list (or array)

In [7]:
print(py_characters[0])
print(np_actors[2])
print(py_actors[-3])


Forrest Gump
Daniel Craig
Tom Hanks


### 1.3 Accessing data from a dictionary

In [8]:
print(characters_info["Wade Wilson"])

Ryan Reynolds


In [9]:
characters_info.keys()

dict_keys(['Forrest Gump', 'Wade Wilson', 'James Bond'])

In [10]:
characters_info.values()

dict_values(['Tom Hanks', 'Ryan Reynolds', 'Daniel Craig'])

### 1.4 Higher dimensional lists

In [11]:
py_characters_info = [["Forrest Gump","Tom Hanks"],
                     ["Wade Wilson","Ryan Reynolds"],
                     ["James Bond","Daniel Craig"]]
print(py_characters_info)

[['Forrest Gump', 'Tom Hanks'], ['Wade Wilson', 'Ryan Reynolds'], ['James Bond', 'Daniel Craig']]


## 2 Lists vs. Arrays

### 2.1 Size

In [19]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [14]:
print(len(py_list_2d))
print(len(np_array_2d))
print(np_array_2d.shape)

10
10
(10, 2)


In [30]:
py_list_3d = [[[1,"one"],["Adam","A"]],
              [[2,"two"], ["Ben","B"]], 
              [[3,"three"], ["Charlie","C"]]]

np_array_3d = np.array(py_list_3d)
print(np_array_3d.shape)
#3d shape of an array, first layer has 3 items, second and third layer have 2 items

(3, 2, 2)


### 2.2 Arrays are fussy about type

In [32]:
py_list = [1, 1.5, 'A']
np.array(py_list)

array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number

In [47]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array
        
print(np_array + 10)
#returns np_array with 10 added to each value
#similar to for i in py_list, i += 10

print(py_list + 10)
#this doesn't work, because you can't add values to a list this way

[11 12 13 14 15]


TypeError: can only concatenate list (not "int") to list

### 2.4 Adding another list

In [42]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

print(py_list_1 + py_list_2)
print(np_array_1 + np_array_2)

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]
[11 22 33 44 55]


### 2.5 Multiplying by a Number

In [45]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

print(py_list * 3)
print(np_array * 3)


[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 3  6  9 12 15]


### 2.6 Squaring

In [49]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

#print(py_list**2)
#this won't work, since you obviously can't square a list

print(np_array**2)
#This squares each of the individual values inside the array

[ 1  4  9 16 25]


### 2.7 Asking questions

In [54]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

print(py_list == 3)
print(py_list == 5)
#print(py_list < 3)
#this doesn't work, makes no sense comparing these

print(np_array == 3)
print(np_array == 2)
print(np_array<= 4)

False
False
[False False  True False False]
[False  True False False False]
[ True  True  True  True False]


### 2.8 Mathematics

In [55]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [58]:
print(sum(py_list),
      max(py_list),
      min(py_list),
      sep = "\n")

15
5
1


In [65]:
print(py_list.sum())
#doesn't work like this, lists don't accept this method

AttributeError: 'list' object has no attribute 'sum'

In [64]:
print(np_array.sum(),
     np_array.mean(),
     np_array.max(),
     np_array.min(),
     sep = "\n")
#np arrays have a bunch of inbuilt methods that you can use!

15
3.0
5
1


## Exercise 1 :  Total recall?

1. Similarities between lists and arrays
    1. Lists and arrays are both mutable and can be numerically indexed, since the order of items is important.
    2. Lists and arrays allow for the storing of many different items, and can be one dimensional, two dimensional, three dimensional, or even more! Depends on the layers of []s you want to use.
2. Differences between lists and arrays
    1. Lists can contain values of different types with no problem, but arrays cannot. All values have to be of the same type
    2. Function calls or method calls on lists and arrays tend to result in different results, since function calls on lists operate on the entire list whereas method calls on arrays operate on individual values within the list
3. Dictionaries are a mutable datatype where there are key/value pairs for each entry, and order does not matter. For each key, there is an associated value.

## Exercise 2 :  Index me

In [66]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
print(py_list[0])                    # Prints 'a1'
print(py_list[2])                    # Prints 'c3'
print(py_list[4])                    # Prints 'e5'
print(py_list[6])                    # Prints 'g7'
print(py_list[8])   # Prints 'i9'

a1
c3
e5
g7
i9


## Exercise 3 :  Capitalise Heros

In [68]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper()
superhero_info["Natasha Romanoff"] = superhero_info["Natasha Romanoff"].upper()
superhero_info["Stephen Strange"] = superhero_info["Stephen Strange"].upper()
print(superhero_info)

{'Natasha Romanoff': 'BLACK WIDOW', 'Tony Stark': 'IRON MAN', 'Stephen Strange': 'DOCTOR STRANGE'}


## Exercise 4 :  How many ones

In [6]:
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]                  
np_numbers = np.array(numbers)
np_ones = (np_numbers == 1)
print (f'There are {np_ones.sum()} ones in this list.')


There are 9 ones in this list.
