<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

##### FYI: Subsetting just means to select. Indexing and slicing are just 2 different ways of subsetting a list, array, or string

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [1]:
import numpy as np

py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list
#x = np_array

x[-1000::2]

['a1', 'c3', 'e5', 'g7', 'i9']

### 1.2 Subsetting by masking (Arrays only)

In [24]:
np_array = np.array([0,1,2,3,4,5,6,7,8,9,10,11,100,101,102,103,104,105,106])
mask = (np_array % 2) == 0

print(np_array)
print(mask)              #the values themselves are hidden from you but they still exist
print(np_array[mask])      #we reveal the values that were hidden/masked by turning them into an np array again

#an alternative way to do this masking and revealing is:
print(np_array[np_array%2 == 0])

[  0   1   2   3   4   5   6   7   8   9  10  11 100 101 102 103 104 105
 106]
[ True False  True False  True False  True False  True False  True False
  True False  True False  True False  True]
[  0   2   4   6   8  10 100 102 104 106]
[  0   2   4   6   8  10 100 102 104 106]


In [3]:
#There are additional operations you can carry out 
#Additional operations and filters onto your masking/unmasking

np_array = np.array([0,1,2,3,4,5,6,7,8,9,10,11,100,101,102,103,104,105,106])

print(np_array[np_array%2 == 0])

print(np_array[~(np_array%2 == 0)])      #You use ~ in numpy arrays for NOT operator
print((np_array[np_array >100]) == (np_array[~(np_array<=100)]))    #Another example of NOT operator usage

print(np_array[(np_array < 103) & (np_array > 4)])     #You use % for AND operator

print(np_array[(np_array < 5) | (np_array >= 101)]) #You use | for OR operator

[  0   2   4   6   8  10 100 102 104 106]
[  1   3   5   7   9  11 101 103 105]
[ True  True  True  True  True  True]
[  5   6   7   8   9  10  11 100 101 102]
[  0   1   2   3   4 101 102 103 104 105 106]


### 1.3 Indexing & Slicing 2D Lists

In [4]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

print(py_list_2d[3])
print(py_list_2d[3][0])
print(py_list_2d[:4][1])       #py_list_2d[:4] returns another list, and then [1] indexes the second item (index 1) in that list
print(py_list_2d[3:6][0])

[4, 'D']
4
[2, 'B']
[4, 'D']


### 1.4 Indexing & Slicing 2D Arrays

In [5]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

print(py_list_2d)

np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])
print(np_array_2d)

#look how much nicer the printing formatting is on arrays than on lists! :D

[[1, 'A'], [2, 'B'], [3, 'C'], [4, 'D'], [5, 'E'], [6, 'F'], [7, 'G'], [8, 'H'], [9, 'I'], [10, 'J']]
[['1' 'A']
 ['2' 'B']
 ['3' 'C']
 ['4' 'D']
 ['5' 'E']
 ['6' 'F']
 ['7' 'G']
 ['8' 'H']
 ['9' 'I']
 ['10' 'J']]


In [6]:
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])

print(np_array_2d[3])     #same result as printing a python list index
print(np_array_2d[3,0])   #different syntax from printing a list index! [3,0] instead of [3][0]
print(np_array_2d[:4,1])  #returns item in index [1] of each index from [0] to [3]
print(np_array_2d[3:6,0]) #returns item in index [0] of each index from [3] to [5]
print(np_array_2d[:,0])   #returns item in index [0] for all items in array

['4' 'D']
4
['A' 'B' 'C' 'D']
['4' '5' '6']
['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']


### 1.5 Growing lists

In [7]:
x = [1]*10

#print(x)           #You can type this to display formal proper output
#Alternatively, you can just let Jupyter give you (non printed) output
x

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [8]:
x = [1]
x += [2]
x += [3]
x += ["Hello World!"]
x += [2]
x += [None]
x += [True]
x

[1, 2, 3, 'Hello World!', 2, None, True]

In [9]:
x = [1]
x += [55, 77, 2, "New"]
print(x)

[1, 55, 77, 2, 'New']


In [10]:
x = [55]
x = ["Figure", 45, False, 3] + x
print(x)

['Figure', 45, False, 3, 55]


In [11]:
x = [1]
x.append(2)
x.append("")
x.append(False)
x.append("False")
x.append(1)

print(x)

[1, 2, '', False, 'False', 1]


## 2 Some loose ends

### 2.1 Tuples

In [12]:
a = (1,2,3)     #a tuple
b = [1,2,3]     #a list

print(a[0])
print(b[0])     #printing the identity for lists and tuples is done the same way

b[1] = 20
b += [44]
print(b)        #but, though you can alter and add to lists

#a[1] = 20      #you cannot alter values within the tuple
a += (44,)
a = ("A","10") + a    #but you can add other tuples to the front or back of the tuple
print(a)

1
1
[1, 20, 3, 44]
('A', '10', 1, 2, 3, 44)


### 2.2 Be VERY careful when copying

In [13]:
x = [1, 2, 3, 4, 5]
y = x.copy()             #Not the same as y = x
z = x.copy()             #Not the same as z = x

print(f'The id of x is {id(x)}, and the contents are {x}')
print(f'The id of y is {id(y)}, and the contents are {y}')
print(f'The id of z is {id(z)}, and the contents are {z}')
#The 3 lists are identical, but they are different items within your memory
#This is identifiable by their different IDs

print("\nThe below is a bad example of what happens when you don't use list.copy()\n")
a = [1,2,3,4,5]
b = a
c = a

print(f'The id of a is {id(a)}, and the contents are {a}')
print(f'The id of b is {id(b)}, and the contents are {b}')
print(f'The id of c is {id(c)}, and the contents are {c}')

The id of x is 2380359688576, and the contents are [1, 2, 3, 4, 5]
The id of y is 2380359688384, and the contents are [1, 2, 3, 4, 5]
The id of z is 2380359688768, and the contents are [1, 2, 3, 4, 5]

The below is a bad example of what happens when you don't use list.copy()

The id of a is 2380359688832, and the contents are [1, 2, 3, 4, 5]
The id of b is 2380359688832, and the contents are [1, 2, 3, 4, 5]
The id of c is 2380359688832, and the contents are [1, 2, 3, 4, 5]


In [14]:
x = [1, 2, 3, 4, 5]
y = x.copy()             #Not the same as y = x
z = x.copy()             #Not the same as z = x

x[0] = 10
print(x)
print(y)                 #List y is not changed!

[10, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


## Exercise 1 :  Total recall?

|Term|Brief Description|
|:--|:--|
|Subsetting|Refers to selecting one or more values from a list or array (or tuple?|
|Indexing|Subsetting a single value|
|Slicing|Subsetting a range of values|
|Masking|Checking a condition against the values of an array to form a new array that displays the output of this condition on said array|

## Exercise 2 :  Show me the ‘odd’ letters

In [68]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

np_array_2d_numbers = np.array(np_array_2d[:,0],dtype="int")
#Alternatively
#np_array_2d_numbers = (np.array(np_array_2d[:,0]).astype(int))

mask = (np_array_2d_numbers %2 == 1)
np_array_2d_odds = np_array_2d[mask]
print(f'The letters that correspond to the odd numbers are {np_array_2d_odds[:,1]}.')

The letters that correspond to the odd numbers are ['A' 'C' 'E' 'G' 'I'].
